sudo: false
dist: trusty
language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
addons:
  chrome: stable
before_install:
  - npm install -g npm
  - npm --version
  - npm install -g grunt-cli
