# sudo: false - uncomment when Travis is fixed - https://github.com/kidoju/Kidoju-Widgets/issues/251
sudo: required
dist: trusty
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
addons:
  chrome: stable
before_install:
  - npm install -g npm
  - npm --version
  - npm install -g grunt-cli
