os: linux
dist: xenial
language: node_js
node_js:
  - "15"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
env:
    - NODE_ENV=test FORCE_COLOR=true
addons:
  chrome: stable
before_install:
  - google-chrome --version
  - npm install -g npm
  - npm --version
