# sudo:true until Travis is fixed - https://github.com/kidoju/Kidoju-Widgets/issues/251
sudo: true
dist: trusty
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
addons:
  chrome: stable
before_install:
  - npm install -g npm
  - npm --version
  - npm install -g grunt-cli
