sudo: false
# dist: xenial
language: node_js
node_js:
  - "13"
  - "12"
  - "11"
  - "10"
env:
    - NODE_ENV=test FORCE_COLOR=true
addons:
  chrome: stable
before_install:
  - npm install -g npm
  - npm --version
  - npm install -g grunt-cli
