sudo: false
dist: trusty
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
addons:
  chrome: stable
before_install:
  - npm install -g npm
  - npm --version
  - npm install -g grunt-cli
before_script:
  - "chown root /opt/google/chrome/chrome-sandbox"
  - "chmod 4755 /opt/google/chrome/chrome-sandbox"
